//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaionsParameters
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Parameter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Parameter()
        {
            this.tbl_SetParameter = new HashSet<tbl_SetParameter>();
        }
    
        public int ParameterId { get; set; }
        public string ParameterName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SetParameter> tbl_SetParameter { get; set; }
    }
}
