//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaionsParameters
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Parameters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Parameters()
        {
            this.tbl_ObserveData = new HashSet<tbl_ObserveData>();
        }
    
        public int ParameterId { get; set; }
        public string ParameterName { get; set; }
        public int StationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ObserveData> tbl_ObserveData { get; set; }
        public virtual tbl_Stations tbl_Stations { get; set; }
    }
}
