//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaionsParameters
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ObserveData
    {
        public int ObserveId { get; set; }
        public int ParameterId { get; set; }
        public string Date { get; set; }
        public int Value { get; set; }
    
        public virtual tbl_Parameters tbl_Parameters { get; set; }
    }
}
