//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaionsParameters
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WeatherDbEntities : DbContext
    {
        public WeatherDbEntities()
            : base("name=WeatherDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Stations> tbl_Stations { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_ObserveData> tbl_ObserveData { get; set; }
        public virtual DbSet<tbl_Parameters> tbl_Parameters { get; set; }
    
        public virtual ObjectResult<SP_InfoObserve_Result> SP_InfoObserve(Nullable<int> stationid)
        {
            var stationidParameter = stationid.HasValue ?
                new ObjectParameter("stationid", stationid) :
                new ObjectParameter("stationid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_InfoObserve_Result>("SP_InfoObserve", stationidParameter);
        }
    }
}
